server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mayramedranda17@gmail.com
    password: tqjr ndpd utkd yydn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5433/cosbell
    username: postgres
    password: 1004
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update  # Te recomiendo usar update mientras desarrollas
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

flashbang:
  date: 2025-07-08T12:00:00

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.cosbell.spa: DEBUG

whatsapp:
  phone-number-id: 762898906903494
  access-token: EAAKdUrYs5N8BPA78yaJcVp1etJiqcZAq784uuYK2eKgjEqyXWGERPOyxJXfnqEfq0SuBdG2dkUX7xnV9EMZBYqH99g7lZCCUfc7unOozJdM86hZBYTgWCZBts5ZCdt6KVzhvZACa7gRCOZB938CEYX9WZCedbZCcaZCHhsj3LioZCxgZBvdlg3e3unoDM94WZAYx8fhGUMTbx5ZCvk1yn7XnIZABWc1ar6gBbwuyKeCDTS11qIttOLzJ1AZDZD
